frameworks:
  crewai:
    adapter_import: createCrewAIAdapter
    adapter_module_path: automcp-ts/lib/adapters/crewai.js
    import_comment: "// import { YourCrewAIAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpCrewAIAgent = createCrewAIAdapter(
        new YourCrewAIAgent(),
        name,
        description,
        InputSchema
      );

  langgraph:
    adapter_import: createLangGraphAdapter
    adapter_module_path: automcp-ts/lib/adapters/langgraph.js
    import_comment: "// import { YourLangGraphAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpLangGraphAgent = createLangGraphAdapter(
        new YourLangGraphAgent(),
        name,
        description,
        InputSchema
      );

  llamaindex:
    adapter_import: createLlamaIndexAdapter
    adapter_module_path: automcp-ts/lib/adapters/llamaindex.js
    import_comment: "// import { YourLlamaIndexAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpLlamaIndexAgent = createLlamaIndexAdapter(
        new YourLlamaIndexAgent(),
        name,
        description,
        InputSchema
      );

  openai:
    adapter_import: createOpenAIAdapter
    adapter_module_path: automcp-ts/lib/adapters/openai.js
    import_comment: "// import { YourOpenAIAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpOpenAIAgent = createOpenAIAdapter(
        new YourOpenAIAgent(),
        name,
        description,
        InputSchema
      );

  pydantic:
    adapter_import: createPydanticAdapter
    adapter_module_path: automcp-ts/lib/adapters/pydantic.js
    import_comment: "// import { YourPydanticAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpPydanticAgent = createPydanticAdapter(
        new YourPydanticAgent(),
        name,
        description,
        InputSchema
      );

  mcp-agent:
    adapter_import: createMcpAgentAdapter
    adapter_module_path: automcp-ts/lib/adapters/mcpAgent.js
    import_comment: "// import { YourMcpAgent, llm, app, initializeFn } from './your-agent.js';"
    adapter_definition: |
      const mcpAgentTool = createMcpAgentAdapter(
        new YourMcpAgent(),
        llm,
        app,
        initializeFn,
        name,
        description,
        InputSchema
      );

  express:
    adapter_import: createExpressAdapter
    adapter_module_path: automcp-ts/lib/adapters/express.js
    import_comment: "// import { YourExpressAgent } from './your-agent.js';"
    adapter_definition: |
      const mcpExpressAgent = createExpressAdapter({
        agentInstance: new YourExpressAgent(),
        name: name,
        description: description,
        inputSchema: InputSchema
      });
